# From https://github.com/igorvisi/dotfiles/
# Load antigen
autoload antigen
source ~/.dotfiles/shell/zsh/antigen/antigen.zsh
# Load the oh-my-zsh's library
antigen use oh-my-zsh

antigen bundles <<__EOF__
aperezdc/zsh-fzy
command-not-found
common-aliases
git
git-flow
hlissner/zsh-autopair
igorvisi/zsh-up
last-working-dir
sudo
rupa/z
changyuheng/fz
zsh-users/zsh-autosuggestions
zsh-users/zsh-completions
zsh-users/zsh-history-substring-search
zsh-users/zsh-syntax-highlighting
__EOF__

# antigen theme igorvisi/fibo-zsh-theme fibo
antigen theme https://github.com/denysdovhan/spaceship-prompt spaceship
antigen apply



setopt correct                      # Auto correct typo in commande.
setopt globdots                     # completion to show hidden files
setopt extendedglob                 # Extended globbing. Allows using regular expressions with *
setopt histignorealldups            # Ignore duplicate command in history
setopt histignorespace              # Don't record command prefixe with space
setopt hist_reduce_blanks           # trim blanks
setopt inc_append_history           # Appends every command to the history file once it is executed
setopt share_history                # Reloads the history whenever you use it
setopt prompt_subst                 # enable substitution for prompt
setopt extended_history             # add timestamps to history
setopt prompt_subst                 # enable substitution for prompt
setopt bang_hist                    # !keyword
set -o noclobber                    # Do not override files using `>`, but it's still possible using `>!`

# Load personal global variables like PATH ...
source $HOME/.global
# Load aliases
source $HOME/.aliases
# Useful Shell functions.
source $HOME/.functions


# Load some usefull functions for zsh prompt
source $HOME/.zsh/keymap.zsh
source $HOME/.zsh/syntax-highlighting-filetypes.zsh
source $HOME/.zsh/completions.zsh

# Add bash completion
autoload -U +X bashcompinit && bashcompinit

DISABLE_AUTO_UPDATE=true
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

complete -o nospace -C $HOME/Bin/nomad nomad