# Load personal global variables like PATH ...
source $HOME/.global
# Load aliases
source $HOME/.aliases
# Useful Shell functions.
source $HOME/.functions

autoload -Uz compinit
compinit

# Load sheldon, zsh plugin manager
# https://github.com/rossmacarthur/sheldon
eval "$(sheldon source)"

setopt correct                      # Auto correct typo in commande.
setopt globdots                     # completion to show hidden files
setopt extendedglob                 # Extended globbing. Allows using regular expressions with *
setopt histignorealldups            # Ignore duplicate command in history
setopt histignorespace              # Don't record command prefixe with space
setopt hist_reduce_blanks           # trim blanks
setopt inc_append_history           # Appends every command to the history file once it is executed
setopt share_history                # Reloads the history whenever you use it
setopt prompt_subst                 # enable substitution for prompt
setopt extended_history             # add timestamps to history
setopt prompt_subst                 # enable substitution for prompt
setopt bang_hist                    # !keyword
set -o noclobber                    # Do not override files using `>`, but it's still possible using `>!`



# Load some usefull functions for zsh prompt
source $HOME/.zsh/keymap.zsh
source $HOME/.zsh/syntax-highlighting-filetypes.zsh
source $HOME/.zsh/completions.zsh

DISABLE_AUTO_UPDATE=true
ZSH_AUTOSUGGEST_STRATEGY=(history completion)


# Herd injected PHP binary.
export PATH="/Users/igorvisi/Library/Application Support/Herd/bin/":$PATH


# Herd injected PHP 8.2 configuration.
export HERD_PHP_82_INI_SCAN_DIR="/Users/igorvisi/Library/Application Support/Herd/config/php/82/"


# Herd injected PHP 8.3 configuration.
export HERD_PHP_83_INI_SCAN_DIR="/Users/igorvisi/Library/Application Support/Herd/config/php/83/"


# Herd injected PHP 7.4 configuration.
export HERD_PHP_74_INI_SCAN_DIR="/Users/igorvisi/Library/Application Support/Herd/config/php/74/"
