#!/bin/sh

if [ "$XDG_CURRENT_DESKTOP" = "i3" ]; then
    export QT_PLUGIN_PATH=$HOME/.kde4/lib/kde4/plugins/:/usr/lib/kde4/plugins/
fi

export QT_QPA_PLATFORMTHEME="qt5ct"

# Using GnuPG Agent as a SSH agent
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent
