mode = "dark"

accent = "#61afef"
selection = "#3e4451"
muted = "#5c6370"

background = "#1e2229"
dark_background = "#181b20"
darker_background = "#121419"
lighter_background = "#282c34"

foreground = "#abb2bf"
dark_foreground = "#5c6370"
light_foreground = "#c8ccd4"
bright_foreground = "#ffffff"

red = "#e06c75"
yellow = "#e5c07b"
orange = "#d19a66"
green = "#98c379"
cyan = "#56b6c2"
blue = "#61afef"
magenta = "#c678dd"
brown = "#be5046"

bright_red = "#e06c75"
bright_yellow = "#e5c07b"
bright_green = "#98c379"
bright_cyan = "#56b6c2"
bright_blue = "#61afef"
bright_magenta = "#c678dd"
