[bar]
background = "#1e2229"
background-alpha = 1.0
text = "#abb2bf"
active = "#e06c75"
scale-with-font = true
size-horizontal = 26
size-vertical = 28

[hyprland]
active-border = "#61afef"
active-border-foreground = "#abb2bf"

[controls]
normal-color = "#abb2bf"
normal-fill-alpha = 0.04
normal-border = "#5c6370"
normal-border-width = 1
normal-border-alpha = 0.4
hover-cursor-color = "#abb2bf"
hover-cursor-fill-alpha = 0.08
hover-cursor-border = "#abb2bf"
hover-cursor-border-width = 1
hover-cursor-border-alpha = 0.25
focus-color = "#abb2bf"
focus-fill-alpha = 0.08
focus-border = "#abb2bf"
focus-border-width = 1
focus-border-alpha = 0.25
selected-color = "#abb2bf"
selected-fill-alpha = 0.18
selected-border = "#61afef"
selected-border-width = 0
selected-border-alpha = 1.0
pressed-fill-alpha = 0.22
selection-fill-alpha = 0.35

[spacing]
scale = 1.0
scale-with-font = true

[font]
base-size = 12

[popups]
background = "#1e2229"
background-alpha = 1.0
text = "#abb2bf"
border = "#61afef"
border-alpha = 1.0

[tooltip]
background = "#1e2229"
background-alpha = 0.97
text = "#abb2bf"
border = "#5c6370"
border-alpha = 1.0

[menu]
background = "#1e2229"
background-alpha = 1.0
text = "#abb2bf"
border = "#61afef"
border-alpha = 1.0
scrim = "#1e2229"
scrim-alpha = 0.5
selected-background = "#3e4451"
selected-background-alpha = 1.0
selected-text = "#61afef"
selected-border = "#61afef"
selected-border-alpha = 0.25

[launcher]
background = "#1e2229"
background-alpha = 0.95
text = "#abb2bf"
border = "#61afef"
border-alpha = 1.0
scrim = "#1e2229"
scrim-alpha = 0.5
selected-background = "#3e4451"
selected-background-alpha = 1.0
selected-text = "#61afef"
selected-border = "#61afef"
selected-border-alpha = 0.25
